### ISSUE TITLE
QQ.exe文件消失

### ISSUE THREAD

**Issue by BoXueDuoCai** [LiteLoaderQQNT/QQNTFileVerifyPatch#11]
我在使用前QQ.exe文件还在
在patch结束后文件就没了
一共四行，最后一行是Sig not found然后就按任意键退出
再一看文件没了

**Comment by BoXueDuoCai** [comment]
重装一遍到是没问题了

**Comment by sysrom** [comment]
你是修补过一次了吧，再修补肯定找不到特征码去修改了
文件不是消失了，是另存为QQ.exe.bak了
