### ISSUE TITLE
引入arm64dll后报错

### ISSUE THREAD

**Issue by fluid41** [LiteLoaderQQNT/QQNTFileVerifyPatch#16]
![屏幕截图 2024-08-01 121316](https://github.com/user-attachments/assets/311f3082-c158-48c5-9dcb-a289649da2d9)

**Comment by sysrom** [comment]
QQ版本是多少

**Comment by fluid41** [comment]
报错版本为9.9.12_240715_arm64_01
更新到9.9.12_240729_arm64_01后正常运行
