### ISSUE TITLE
添加 DllHijack 后运行 QQ 报错【Cannot find module】

### ISSUE THREAD

**Issue by wordpure** [LiteLoaderQQNT/QQNTFileVerifyPatch#18]
## 环境信息

- 系统架构：x64
- Windows 版本：Win11 22H2 
- QQNT 版本：240808（9.9.15-26909）
- DllHijack 版本：1.1.0

## 问题

新安装还未启动过的 QQNT，在 QQ.exe 所在目录含有 DllHijack 的 dbghelp.dll 和已配置好 LiteLoaderQQNT 路径的 PatchConfig.json 时，运行 QQ.exe 报错【Cannot find module】，不会显示登录界面。

![图片](https://github.com/user-attachments/assets/35057cf6-0d16-4217-97b4-fd567e2feaf1)

此时即使移走 dbghelp.dll，运行 QQ 也会报错【文件已损坏】。

![图片](https://github.com/user-attachments/assets/aa73376b-08be-47b3-81fc-02221fd10d2c)

需要手动到 resources\app\versions 新建一个压缩包同名目录，将压缩包中的内容提取过去，QQ 才能正常运行。

![图片](https://github.com/user-attachments/assets/02280834-e848-4c61-83bd-0a44fa19f7f9)

## 备注

1. 这里的 QQNT 是用我自己的 Scoop [bucket](https://github.com/wordpure/scoop-air/blob/main/bucket/QQNT.json) 安装的，QQ.exe 所在目录的文件都是 Scoop 从 QQ 安装包的 Files 目录提取所得，和默认安装可能有所不同。

	![图片](https://github.com/user-attachments/assets/09efd99e-299c-49c4-968f-a8a490d9b994)

2. dbghelp.dll 和 PatchConfig.json 也是安装脚本自动配置的，如果只有 dbghelp.dll，或者 PatchConfig.json 的 LiteLoaderQQNT 的路径没有设置，那么 QQ 会自己提取版本号压缩包。后面再设置 LiteLoaderQQNT 的路径，就不会出现上面提到的问题，LiteLoaderQQNT 也可以正常加载。

	![图片](https://github.com/user-attachments/assets/114baaea-9328-4182-8fe2-f18730c6d556)

**Comment by sysrom** [comment]
没遇到过这种奇怪的问题啊（

**Comment by sysrom** [comment]
貌似首次启动必须得让QQNT自己初始化完毕才能装LLQQNT

**Comment by wordpure** [comment]
> 貌似首次启动必须得让QQNT自己初始化完毕才能装LLQQNT

还真是这个问题😂

试着给安装脚本加了个自动提取版本号压缩包的功能，然后运行 QQ，LiteLoaderQQNT 就能正常加载了。

虽然比起 QQ 的初始化少了一些文件，不过貌似提取出来的版本号文件夹才是 LL 必要的内容。

![图片](https://github.com/user-attachments/assets/631bda77-0909-4c58-aec2-94ef0e9bbd3e)

**Comment by sysrom** [comment]
草

**Comment by wordpure** [comment]
> 虽然比起 QQ 的初始化少了一些文件，不过貌似提取出来的版本号文件夹才是 LL 必要的内容。

上面的表达有点歧义🤣

应该说是把压缩包的内容提取到版本号文件夹，再运行 QQ，缺失的那些文件会自动补全，所以要处理的只有提取压缩包那一步。
