### ISSUE TITLE
是否支持或打算支持通过命令行的方式进行修补

### ISSUE THREAD

**Issue by DaveBoy** [LiteLoaderQQNT/QQNTFileVerifyPatch#19]
想把整个过程做成脚本，所以想问一下是否支持或打算支持命令行形式静默修补

**Comment by DaveBoy** [comment]
main分支为exe，是我所想问的。
dll那种目前是可以静默执行的。
或者说这两种更新支持方面或者推荐用哪种

**Comment by sysrom** [comment]
exe式修改文件可以参考 https://github.com/Mzdyl/LiteLoaderQQNT_Install/
dll劫持没有打算支持要通过什么命令行的方式安装，就只是下载文件自己改名就行，写成命令反倒是像恶意软件
