### ISSUE TITLE
请问360报毒是误报吗（我知道这问题听起来很欠揍）

### ISSUE THREAD

**Issue by heerxingen** [LiteLoaderQQNT/QQNTFileVerifyPatch#2]
![image](https://github.com/LiteLoaderQQNT/QQNTFileVerifyPatch/assets/102276349/20583c28-7ca7-4f5f-86a7-21d41dd3bb21)
就是，有点吓人（划掉）
（我用过的软件一般都不会这么问 但是第一次用QQNTFileVerifyPatch）

**Comment by sysrom** [comment]
360的弱智AI过度学习特征了,MSVC编译的东西几乎都会报毒,不放心的话这边建议自己clone repo自行编译使用.

**Comment by heerxingen** [comment]
ok明白
