### ISSUE TITLE
9.9.15-26740无法正常使用

### ISSUE THREAD

**Issue by haihai666** [LiteLoaderQQNT/QQNTFileVerifyPatch#20]
按照正确的方式添加dbghelp文件后修改index.js并检查目录正确后启动qqnt仍然提示文件已损坏

**Comment by sysrom** [comment]
![ScreenShot20240812212920](https://github.com/user-attachments/assets/9268332e-5666-4f4b-ba0d-cc1e6a362df1)

经测试在9.9.15-26740上工作正常

**Comment by miaomiaocatmsg** [comment]
9.9.15-27206 失效

**Comment by 1665169869** [comment]
9.9.15-27206也会无法使用
![image](https://github.com/user-attachments/assets/c666a998-3c56-4034-ae2d-f6aa518206da)

**Comment by sysrom** [comment]
user issue
