### ISSUE TITLE
ARM64劫持DLL以及修补EXE失败

### ISSUE THREAD

**Issue by Abel-j** [LiteLoaderQQNT/QQNTFileVerifyPatch#22]
ARM64 Windows11下修补以及劫持DLL后QQ无法运行，提示ERROR:Sig not found!
QQ版本：9.9.15.27333
系统：Windows11 专业版 24H2 26100.1586 (骁龙855)
附未修补的原版QQ.exe文件：https://www.123pan.com/s/sYvDVv-f6IN.html

**Comment by AnYiEE** [comment]
[dbghelp_x64.dll](https://github.com/LiteLoaderQQNT/QQNTFileVerifyPatch/releases/download/DllHijack_1.1.0/dbghelp_x64.dll)的自动patch也失效了，版本9.9.15.27333，9.9.15.26909正常。

**Comment by Alan-CRL** [comment]
我64位下最新的QQ9915也失效了

**Comment by sysrom** [comment]
最新版本中ARM64特征码应该修复，没有实测因为手头上没有ARM64的设备

至于64位的，我没有出现过失效的问题，建议**卸载所有插件**后重试

**Comment by AnYiEE** [comment]
> 最新版本中ARM64特征码应该修复，没有实测因为手头上没有ARM64的设备
> 
> 至于64位的，我没有出现过失效的问题，建议**卸载所有插件**后重试

我所说的“失效”是指更新之后dll没有自动为js添加require语句，这个阶段应该和插件没什么关系吧。

**Comment by sysrom** [comment]
你配置PatchConfig.json了吗，我没有遇到过这个问题

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Alan-CRL** [comment]
> 我64位下最新的QQ9915也失效了

我使用 PatcherNFixer 的框架方案就没有问题，而 DLLHijackMethod 对于 64 位 QQNT 则没有效果。我确认 64 dll 是放置在正确目录下的。

**Comment by XuJun09** [comment]
9.9.15，使用1.1.1的dll劫持依然提示sig not found

**Comment by AnYiEE** [comment]
> 你配置PatchConfig.json了吗，我没有遇到过这个问题

除了在QQ内过自动和通过winget静默升级QQ，其他东西都很久没动过了，包括PatchConfig.json。之前的版本都可以正常在升级之后第一次打开的时候请求管理员权限按PatchConfig.json修补那个js。

**Comment by sysrom** [comment]
arm64 的重下 1.1.1, 应该没问题了

**Comment by sysrom** [comment]
> > 最新版本中ARM64特征码应该修复，没有实测因为手头上没有ARM64的设备
> > 至于64位的，我没有出现过失效的问题，建议**卸载所有插件**后重试
> 
> 我所说的“失效”是指更新之后dll没有自动为js添加require语句，这个阶段应该和插件没什么关系吧，并且我很长时间都没有安装、更新和删除过插件了，插件们的设置也很久没改过了。
这个的话我建议去resources\app\app_launcher下面看看是不是还有一个PatchConfig.json 不知道什么原因写到那里去了

**Comment by AnYiEE** [comment]
> 是不是还有一个PatchConfig.json

升级9.9.15.27333遇到这个问题之后，我随即看了下resources\app\app_launcher里的js，发现没有被修补。同时看到这个目录多了个PatchConfig.json，就删掉了，仅保留了QQ根目录的那个。

但重新打开QQ，还是没有像9.9.15.26909及其之前的版本一样自动请求管理员权限patch QQ.exe，而是直接进了QQ，QQ.exe的签名和js里的内容都没变化，这时的dbghelp_x64.dll 1.1.0还按原样在QQ根目录。

**Comment by sysrom** [comment]
> > 是不是还有一个PatchConfig.json
> 
> 升级9.9.15.27333遇到这个问题之后，我随即看了下resources\app\app_launcher里的js，发现没有被修补。同时看到这个目录多了个PatchConfig.json，就删掉了，仅保留了QQ根目录的那个。
> 
> 但重新打开QQ，还是没有像9.9.15.26909及其之前的版本一样自动请求管理员权限patch QQ.exe，而是直接进了QQ，QQ.exe的签名和js里的内容都没变化，这时的dbghelp_x64.dll 1.1.0还按原样在QQ根目录。

你把PatchConfig.json丢到resources\app\app_launcher 里面, 不知道什么原因他不读不到根目录的文件了

**Comment by AnYiEE** [comment]
> 你把PatchConfig.json丢到resources\app\app_launcher 里面, 不知道什么原因他不读不到根目录的文件了

如此做之后，js正常被修改了，但QQ.exe的签名还是原版的…不知道怎么回事，手动用PatcherNFixer修补了下，总归可以正常用了。

**Comment by sysrom** [comment]
?????  因为压根没有修改PE文件啊，DLLHijack在内存里面完成文件验证修补

________________________________
发件人: 安忆 ***@***.***>
发送时间: 2024年9月2日 1:03
收件人: LiteLoaderQQNT/QQNTFileVerifyPatch ***@***.***>
抄送: sysROM ***@***.***>; Comment ***@***.***>
主题: Re: [LiteLoaderQQNT/QQNTFileVerifyPatch] ARM64劫持DLL以及修补EXE失败 (Issue #22)


你把PatchConfig.json丢到resources\app\app_launcher 里面, 不知道什么原因他不读不到根目录的文件了

如此做之后，js正常被修改了，但QQ.exe的签名还是原版的…不知道怎么回事，手动用PatcherNFixer修补了下，总归可以正常用了。

―

**Comment by AnYiEE** [comment]
> ????? 因为压根没有修改PE文件啊，DLLHijack在内存里面完成文件验证修补

原来是这样的嘛…之前只管用了也没管它怎么实现的，看来是想当然了，不好意思…

但确实是在把json移过去之后，运行QQ之后正常弹了管理员授权，js也正常加了require语句，但没有弹登录窗口，所以找到了PatcherNFixer。

**Comment by AnYiEE** [comment]
> 但没有弹登录窗口

应该找到原因了。在QQ内升级之后安装程序会自动启动QQ，但此次启动不会请求管理员权限（之前也是这样），而是直接出现登录窗口，登录进去也是原版的状态。所以我往往都会在它自动启动刚弹出登录窗口的时候直接右键托盘图标点退出，然后再开一次QQ，这次就能正常请求管理员权限了。但这回不知怎么，点了退出登录窗口和托盘图标是没了，但进程还在（我打算把dll换成新的，在移动的时候提示被占用才发现），结束进程就正常了，估计是这个原因吧。
