### ISSUE TITLE
QQ9.9.15-28060版本下无法使用

### ISSUE THREAD

**Issue by bocchi810** [LiteLoaderQQNT/QQNTFileVerifyPatch#24]
QQ目录下的dbghelp.dll消失了，尝试直接把修补的dll复制到QQ同级目录，也没法打开QQ

**Comment by cow-your-sister** [comment]
同
![image](https://github.com/user-attachments/assets/64a29e7d-26a5-4d2d-9b03-460d802333af)

**Comment by singularity2000** [comment]
https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues/417
https://github.com/Mzdyl/LiteLoaderQQNT_Install/issues/130
看来只能等了

**Comment by Natural12349978** [comment]
一不小心更新到9.9.15-28131 
寄[捂脸]

**Comment by QianYI-Yan** [comment]
回滚19号之前的版本吧，傻逼腾讯
