### ISSUE TITLE
28131用不了了

### ISSUE THREAD

**Issue by jiang068** [LiteLoaderQQNT/QQNTFileVerifyPatch#25]
QQ更新太快了……并且我记得是已经取消勾选了自动更新，今天打开还没登录进去就自动更新了最新版，硬控我10分钟；只能说QQ太逆天了

**Comment by XiaozhiSans** [comment]
实测1.1.2的dbghelp.dll可以正常使用
![image](https://github.com/user-attachments/assets/7cadd092-5880-426f-8594-979d7a0b2218)

**Comment by miaomiaocatmsg** [comment]
![QQ20240930-020449](https://github.com/user-attachments/assets/4666349e-1b18-43dd-971b-9c2c6c7cbf1c)


实测无问题~~

**Comment by jiang068** [comment]
可是我的为什么还不行👀按照之前一样设置的
![B1423EDA4DB3E0F458D65FCAAADEC1E0](https://github.com/user-attachments/assets/e73e68fd-60b1-42c4-81fd-11e936f8ba4b)

**Comment by jiang068** [comment]
用了liteloaderqqnt.github.io的最新方法重新安装了一下，现在可以了，谢谢大家！
