### ISSUE TITLE
求助，正确放置 dbghelp.dll 后导致 QQ 启动时闪退

### ISSUE THREAD

**Issue by Alan-CRL** [LiteLoaderQQNT/QQNTFileVerifyPatch#26]
尝试 28060 和 28418 版本均无法。主要体现是启动 QQ 后，任务管理器识别到进程，紧接着 QQ 就退出了，期间没有任何界面显示和报错。升级前一切正常，当时 Loader 版本是 1.2.2，升级后出现这个问题。dbghelp.dll 移除后 QQ 正常启动报损坏。系统 Windows 11 23H2。

**Comment by sysrom** [comment]
![Snipaste_2024-10-09_12-49-32](https://github.com/user-attachments/assets/f532e33e-22ea-437d-a16d-6ffe61628d73)

无法复现

**Comment by Alan-CRL** [comment]
经过我彻底卸载后重装，现在问题已经解决，非常抱歉打扰了您的时间。问题出现的主要原因应该是升级后本地文件混乱的缘故。
