### ISSUE TITLE
9.9.15-28498失效

### ISSUE THREAD

**Issue by yhzcake** [LiteLoaderQQNT/QQNTFileVerifyPatch#29]
因为一个插件不支持老版本qq,然后选择更新,然后就悲剧了
大致确定是修补寄了

**Comment by yhzcake** [comment]
或者谁给个28060的安装包..

**Comment by Alan-CRL** [comment]
28498 可以的，你需要把现在的 28498 卸载，然后把整个 QQNT 目录清空，然后再安装就可以修补了

**Comment by ReallyChooseC** [comment]
> 28498 可以的，你需要把现在的 28498 卸载，然后把整个 QQNT 目录清空，然后再安装就可以修补了

9.9.16-28788按照这个方法操作后仍不可用，同时没有生成PatchConfig.json

**Comment by ReallyChooseC** [comment]
> > 28498 可以的，你需要把现在的 28498 卸载，然后把整个 QQNT 目录清空，然后再安装就可以修补了
> 
> 9.9.16-28788按照这个方法操作后仍不可用，同时没有生成PatchConfig.json

修正一下，修补可用，但PatchConfig.json无效
