### ISSUE TITLE
安装patch文件后，手心输入法无法输入中文

### ISSUE THREAD

**Issue by cntvc** [LiteLoaderQQNT/QQNTFileVerifyPatch#6]
QQNT版本：9.9.7-21804 (64位)
patch文件版本：1.0.1

根据 LiteLoaderQQNT 安装教程，在移除导入框架的 JS 代码后，只放 patch 文件也会导致该问题

**Comment by sysrom** [comment]
删除patch的dll或者还原原版文件问题还存在吗

________________________________
发件人: Charlie Brown ***@***.***>
发送时间: 2024年3月19日 16:56
收件人: LiteLoaderQQNT/QQNTFileVerifyPatch ***@***.***>
抄送: Subscribed ***@***.***>
主题: [LiteLoaderQQNT/QQNTFileVerifyPatch] 安装patch文件后，手心输入法无法输入中文 (Issue #6)


QQNT版本：9.9.7-21804 (64位)
patch文件版本：1.0.1

根据 LiteLoaderQQNT 安装教程，在移除导入框架的 JS 代码后，只放 patch 文件也会导致该问题

―

**Comment by cntvc** [comment]
> 删除patch的dll或者还原原版文件问题还存在吗

删除后就恢复正常了

**Comment by sysrom** [comment]
已修复
