### ISSUE TITLE
使用 Dll 会导致 QQ 无法使用命令行参数

### ISSUE THREAD

**Issue by PRO-2684** [LiteLoaderQQNT/QQNTFileVerifyPatch#7]
使用 Dll method 时，给 QQ 执行时加上启动参数，会导致其仍然报“文件已损坏”的错误；改为使用 patcher 就正常工作

**Comment by sysrom** [comment]
这个嘛，是因为我在DLLMain中判断了进程命令行参数是否有-- 判断是否为主进程导致的，因为Dll劫持到子进程可能会导致一些奇奇怪怪的问题

**Comment by sysrom** [comment]
已修复

**Comment by Whuihuan** [comment]
240403的版本使用多账号同时登陆的时候仍旧报文件损坏
