### ISSUE TITLE
一种更简单的过校验方式

### ISSUE THREAD

**Issue by msojocs** [LiteLoaderQQNT/QQNTFileVerifyPatch#8]
1. 创建一个默认的 `index.default.js`，内容未安装时的 `index.js` 内容; 而 `index.js` 则为修改的内容。
2. 拦截CreateFileW
3. 如果第一次访问 `index.js`，判定为校验文件，返回 `index.default.js` 的fd
4. 否则返回 `index.js` 的fd

我已基于次思路实现;

https://github.com/project-yukihana/Yukihana-patch

**Comment by sysrom** [comment]
这个项目最先开始时要过package.js的修改（别问，问就是我那时候以为旧框架过了修改文件也能用），现在的方案是直接Hook负责校验函数，理论上他校验任何资源我这里都可以无视，其次就是QQNT安装时候目录没有给Users写入，想要创建文件需要以管理员身份运行才能创建文件

**Comment by msojocs** [comment]
确实，我忘了本项目的关联项目还会动到package.json之类的问题。（可能用map之类方法能处理多个文件？）
创建文件可以用临时文件，这个好办。

可能用map之类方法能处理多个文件？就像一个映射表。
当然，这只是为了避免频繁修改验证函数签名的一个条路，可用可不用。

**Comment by msojocs** [comment]
已完成配置化
